Repair configure.sh.in
* check $targetqmake only after setting it (if -qmake is specified)
* when -qmake isn't specified, don't skip setting $targetqmake because QTDIR is set
* improve error messages in both cases

diff --git a/configure.sh.in b/configure.sh.in
--- a/configure.sh.in
+++ b/configure.sh.in
@@ -142,30 +142,6 @@ EOF
     exit 1
 }
 
-if [ "$targetqmake" != "" ] ; then
-    if [ -z "$QTDIR" ] ;  then
-        QTDIR="$($targetqmake -query QT_INSTALL_PREFIX)"
-        if [ $? -ne 0 ] ; then
-            QTDIR=
-        fi
-    fi
-else
-    for qmk in qmake qmake-qt5 qmake-qt4
-    do
-        which "$qmk" >/dev/null 2>&1
-        if [ $? -eq 0 -a -z "$QTDIR" ]
-        then
-            QTDIR="$($qmk -query QT_INSTALL_PREFIX)"
-            if [ $? -eq 0 ]
-            then
-                targetqmake=$qmk
-                break
-            fi
-        fi
-    done
-fi
-
-[ -z "$QTDIR" ] && die "You need QTDIR defined, or either qmake or qmake-qt5 or qmake-qt4 in the PATH"
 
 while [ $# -ne 0 ] ; do
     case "$1" in
@@ -245,6 +221,29 @@ while [ $# -ne 0 ] ; do
     esac
     shift
 done
+
+if [ -n "$targetqmake" ] ; then
+    if [ -z "$QTDIR" ] ;  then
+        QTDIR="$($targetqmake -query QT_INSTALL_PREFIX)"
+        if [ $? -ne 0 ] ; then
+            die "$targetqmake -query QT_INSTALL_PREFIX gave an error"
+        fi
+    fi
+else
+    for qmk in qmake qmake-qt5 qmake-qt4
+    do
+        which "$qmk" >/dev/null 2>&1
+        if [ $? -eq 0 -a -z "$targetqmake" ] ; then
+            QTDIR="$($qmk -query QT_INSTALL_PREFIX)"
+            if [ $? -eq 0 ] ; then
+                targetqmake=$qmk
+                break
+            fi
+        fi
+    done
+    [ -z "$targetqmake" ] && die "You need qmake or qmake-qt5 or qmake-qt4 in the PATH"
+fi
+
 
 find . -name debug -o -name release -o -name Makefile\* | xargs rm -rf
 
